Development
dpak1999/github-wars pull request #1
Opened 2020-12-26 19:50 UTC by dpak1999

2020-12-28 15:08 UTC, dpak1999 commented
@dipakkr please review

2020-12-29 11:21 UTC, dipakkr requested changes

2020-12-29 11:21 UTC, dipakkr commented on src/Components/Battle.js
> +          <Col lg={6} sm={12} key={playerOneData.id}>
From line No. 41 to line 68 content could be a Component, as you will be reusing it in the player 2 modules. 

Whenever there are repetitive pls move to a new component and handle the data with props to increase the reusability.

2020-12-29 11:21 UTC, dipakkr commented on src/Components/Battle.js
> +          <Col md={6} sm={12}>
same for this content also. You can move it to a new Component and render that Component instead of using HTML component on parent page.

2020-12-29 11:21 UTC, dipakkr commented on src/Components/PopularRepositories.js
> +      <ul className="repo-navigation">
Repo Navigation can be moved to a new Component.

2020-12-29 11:21 UTC, dipakkr commented on src/Components/PopularRepositories.js
> +          <Row>
The list of repositories can be moved to a new component.

2020-12-29 15:52 UTC, dpak1999 commented
@dipakkr refactored

2020-12-29 16:43 UTC, dipakkr approved these changes

2020-12-29 17:27 UTC, merged